### ISSUE TITLE
Plugin crashes when creating powerbi_workspace_access resource

### ISSUE THREAD

**Issue by 00kkcp9230** [codecutout/terraform-provider-powerbi#59]
Hi,
I am trying to create a  powerbi_workspace_access resource using v1.4.1 version

Here is the actual definition of the resource with masked Ids

```
resource "powerbi_workspace_access" "test" {
  workspace_id            = "XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" 
  group_user_access_right = "Viewer"
  identifier              = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX" 
  principal_type          = "Group"
}
```

When I run terraform apply the plugin crashes with the following stack trace

```
Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

powerbi_workspace_access.test: Creating...
╷
│ Error: Request cancelled
│ 
│   with powerbi_workspace_access.test,
│   on test.tf line 109, in resource "powerbi_workspace_access" "test":
│  109: resource "powerbi_workspace_access" "test" {
│ 
│ The plugin.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵

Stack trace from the terraform-provider-powerbi_v1.4.1 plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xd94ca8]

goroutine 83 [running]:
github.com/codecutout/terraform-provider-powerbi/internal/powerbi.addGroupUser(0xc0000d7340, 0x105d320, 0xc000780c80, 0x2, 0x1a70400)
        github.com/codecutout/terraform-provider-powerbi/internal/powerbi/resource_workspace_access.go:102 +0x458
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Resource).Apply(0xc0000d4750, 0xc00008bd60, 0xc000729100, 0x105d320, 0xc000780c80, 0xf0cf01, 0xc0004f0de8, 0xc000117e60)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/resource.go:310 +0x365
github.com/hashicorp/terraform-plugin-sdk/helper/schema.(*Provider).Apply(0xc0000f6280, 0xc0005e7a38, 0xc00008bd60, 0xc000729100, 0xc0001f95e8, 0xc0005460a8, 0xf0ed00)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/helper/schema/provider.go:294 +0x99
github.com/hashicorp/terraform-plugin-sdk/internal/helper/plugin.(*GRPCProviderServer).ApplyResourceChange(0xc000780688, 0x12d2d40, 0xc0001170b0, 0xc0000d67e0, 0xc000780688, 0xc0001170b0, 0xc00008fba0)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/helper/plugin/grpc_provider.go:885 +0x8b4
github.com/hashicorp/terraform-plugin-sdk/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x102b320, 0xc000780688, 0x12d2d40, 0xc0001170b0, 0xc00011ad20, 0x0, 0x12d2d40, 0xc0001170b0, 0xc0001fe280, 0x266)
        github.com/hashicorp/terraform-plugin-sdk@v1.16.0/internal/tfplugin5/tfplugin5.pb.go:3305 +0x217
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0007b48c0, 0x12de960, 0xc000702900, 0xc0005a2200, 0xc00044cd50, 0x1a356e0, 0x0, 0x0, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1171 +0x50a
google.golang.org/grpc.(*Server).handleStream(0xc0007b48c0, 0x12de960, 0xc000702900, 0xc0005a2200, 0x0)
        google.golang.org/grpc@v1.30.0/server.go:1494 +0xccd
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0007961a0, 0xc0007b48c0, 0x12de960, 0xc000702900, 0xc0005a2200)
        google.golang.org/grpc@v1.30.0/server.go:834 +0xa1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.30.0/server.go:832 +0x204

Error: The terraform-provider-powerbi_v1.4.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

What is interesting is that a call to powerbi API is actually made and when I check the powerbi I can see that access to specified workspace have been granted correctly to given group. 
Because of this crash, the resource is never added to the state file.

**Comment by jarnawer** [comment]
I'm facing the same issue...Any help?
